const canvas=document.querySelector('#cosmos'),ctx=canvas.getContext('2d'),motion=document.querySelector('#motion'),media=matchMedia('(prefers-reduced-motion:reduce)'),flower=new Image(),sun=new Image(),atlas=new Image();
let w=0,h=0,cx=0,cy=0,unit=1,paused=media.matches,time=0,last=0,stars=[],dust=[],petals=[],sparks=[],comets=[],nextComet=0,boost=0,targetBoost=0,trip=0,px=0,py=0,mx=0,my=0,ready=false,ripples=[],cursorX=-1000,cursorY=-1000,viewScale=1,sunReady=false,atlasReady=false,zoom=1,entered=false;
const planets=Array.from({length:32},(_,i)=>({ring:i%6,angle:i*2.399,speed:(i%2?1:-1)*(.16+(i%4)*.035),size:25+(i%4)*10,tilt:i*.71,type:i%5}));

const phrases=['Eres mi rincón favorito','Contigo, todo florece','Gracias por estar aquí','Tu sonrisa ilumina mi universo','Un universo de cosas bonitas','Qué bonito coincidir contigo','Cada estrella guarda un deseo','Para ti, todas estas flores','Tú haces mis días más bonitos','Siempre hay luz para ti','Que nunca te falten sonrisas','Mi galaxia florece contigo'];
function drawSun(){const x=cx+px*14,y=cy+py*10,size=(w<650?142:220)*viewScale*(1+Math.sin(time*.9)*.035);if(!sunReady){drawFlower(x,y,size,time*.12);return}ctx.save();ctx.translate(x,y);ctx.rotate(time*.12);ctx.globalCompositeOperation='screen';ctx.drawImage(sun,-size/2,-size/2,size,size);ctx.restore()}
function drawPhrases(front){const count=w<650?6:12;for(let i=0;i<count;i++){const a=i/count*Math.PI*2+time*(i%2?.065:-.075),depth=Math.sin(a);if((depth>=0)!==front)continue;const radius=unit*(.54+(i%3)*.12)*viewScale,x=cx+Math.cos(a)*radius+px*20,y=cy+depth*radius*.55+py*14;const text=phrases[i*(w<650?2:1)],fontSize=(w<650?14:15)+(depth+1)*1.5;ctx.save();ctx.font=`${fontSize}px Georgia,serif`;ctx.textAlign='center';ctx.textBaseline='middle';const half=ctx.measureText(text).width/2;const tx=Math.max(half+12,Math.min(w-half-12,x));ctx.globalAlpha=.36+(depth+1)*.23;ctx.shadowColor='#b675ed';ctx.shadowBlur=9;ctx.fillStyle='#e0c2fc';ctx.fillText(text,tx,y);ctx.restore()}}

function resize(){w=innerWidth;h=document.querySelector('.universe').offsetHeight;const ratio=Math.min(devicePixelRatio||1,2);canvas.width=w*ratio;canvas.height=h*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);cx=w*(w<650?.5:.62);cy=h*(w<650?.57:.53);unit=w<650?w*.95:Math.min(w*.48,h*.79);stars=Array.from({length:w<650?260:550},()=>({x:Math.random()*w,y:Math.random()*h,z:Math.random()*.8+.2,r:Math.random()*1.1+.25,p:Math.random()*6.28}));dust=Array.from({length:w<650?250:600},(_,i)=>({a:Math.random()*6.28,r:.1+Math.random()*.65,arm:i%3,p:Math.random(),size:Math.random()*1.2+.3}));petals=Array.from({length:w<650?14:26},()=>({x:Math.random()*w,y:Math.random()*h,z:Math.random()*.6+.4,a:Math.random()*6.28,s:.15+Math.random()*.4}));render()}
function drawFlower(x,y,size,angle,alpha=1,type=0){if(!ready)return;ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.globalAlpha=alpha;ctx.globalCompositeOperation='screen';if(type>0&&atlasReady){const cell=atlas.naturalWidth/2,cellH=atlas.naturalHeight/2,index=type-1;ctx.drawImage(atlas,(index%2)*cell,Math.floor(index/2)*cellH,cell,cellH,-size/2,-size/2,size,size)}else ctx.drawImage(flower,0,0,1024,735,-size/2,-size*.36,size,size*.72);ctx.restore()}
function ringPoint(r,a){const radius=unit*(.18+r*.105)*viewScale,x=Math.cos(a)*radius,y=Math.sin(a)*radius*.37;return{x:cx+x*.96-y*.33+px*14,y:cy+x*.14+y+py*10,z:Math.sin(a)}}
function render(){ctx.clearRect(0,0,w,h);const travel=boost;for(const s of stars){const x=s.x+px*s.z*20,y=s.y+py*s.z*15,alpha=.2+.5*(Math.sin(time*.7+s.p)+1)/2;ctx.fillStyle=`rgba(224,209,255,${alpha})`;if(travel>.15){ctx.strokeStyle=`rgba(222,189,255,${alpha*travel*.5})`;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(x-cx)*travel*.06*s.z,y+(y-cy)*travel*.06*s.z);ctx.stroke()}ctx.beginPath();ctx.arc(x,y,s.r,0,6.28);ctx.fill()}
ctx.save();ctx.translate(cx+px*14,cy+py*10);ctx.scale(viewScale,viewScale);ctx.rotate(.14);const glow=ctx.createRadialGradient(0,0,5,0,0,unit*.46);glow.addColorStop(0,'#a465ef35');glow.addColorStop(.3,'#773bb321');glow.addColorStop(1,'#652d9700');ctx.fillStyle=glow;ctx.fillRect(-unit,-unit,unit*2,unit*2);for(const d of dust){const a=d.a+time*.075+d.r*5+d.arm*2.094,r=d.r*unit;ctx.fillStyle=`rgba(${d.arm===1?'146,158,245':'187,128,239'},${.12+d.p*.34})`;ctx.beginPath();ctx.arc(Math.cos(a)*r,Math.sin(a)*r*.34,d.size,0,6.28);ctx.fill()}for(let i=0;i<6;i++){ctx.strokeStyle=`rgba(186,127,242,${.18-i*.019})`;ctx.lineWidth=.8;ctx.beginPath();ctx.ellipse(0,0,unit*(.18+i*.105),unit*(.18+i*.105)*.37,0,0,6.28);ctx.stroke()}ctx.restore();
drawPhrases(false);for(const p of planets){for(let j=1;j<=16;j++){const a=p.angle+time*p.speed,point=ringPoint(p.ring,a-j*.018*Math.sign(p.speed));ctx.fillStyle=`rgba(194,143,255,${(1-j/17)*.23})`;ctx.beginPath();ctx.arc(point.x,point.y,Math.max(.4,1.9-j*.085),0,6.28);ctx.fill()}}
const bodies=planets.map(p=>({...p,...ringPoint(p.ring,p.angle+time*p.speed)})).sort((a,b)=>a.z-b.z);function body(p){const near=Math.max(0,1-Math.hypot(p.x-cursorX,p.y-cursorY)/80);const size=(p.size*(w<650?.77:1.12))*(1+p.z*.2)*viewScale*(1+near*.25);drawFlower(p.x,p.y,size,time*.13+p.tilt,.7+(p.z+1)*.15,p.type)}bodies.filter(p=>p.z<0).forEach(body);drawSun();bodies.filter(p=>p.z>=0).forEach(body);drawPhrases(true);
if(ready){ctx.save();ctx.globalCompositeOperation='screen';for(const p of petals){ctx.save();ctx.translate(p.x+px*p.z*18,p.y+py*p.z*15);ctx.rotate(p.a+time*p.s*.3);ctx.globalAlpha=p.z*.5;const size=9+p.z*12;ctx.drawImage(flower,140,250,210,165,-size/2,-size/2,size,size*.8);ctx.restore()}ctx.restore()}
for(const c of comets){const g=ctx.createLinearGradient(c.x,c.y,c.x-100,c.y-40);g.addColorStop(0,`rgba(245,220,255,${c.life})`);g.addColorStop(1,'#a668ea00');ctx.strokeStyle=g;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(c.x-100,c.y-40);ctx.stroke();drawFlower(c.x,c.y,14+c.life*7,time*.5,c.life*.75)}for(const r of ripples){ctx.strokeStyle=`rgba(193,144,255,${Math.max(0,r.life)*.4})`;ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(r.x,r.y,r.radius,r.radius*.55,-.2,0,6.28);ctx.stroke()}for(const s of sparks){ctx.fillStyle=`rgba(219,174,255,${Math.max(0,s.life)})`;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,6.28);ctx.fill()}}
function burst(x,y){if(paused)return;ripples.push({x,y,radius:5,life:1});for(let i=0;i<40;i++){const a=Math.random()*6.28,v=Math.random()*2.4+.5;sparks.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,r:Math.random()*1.8+.5,life:1})}}
function frame(now){const dt=Math.min((now-last)/1000,.04);last=now;if(entered&&!paused&&!document.hidden){boost+=(targetBoost-boost)*dt*2;time+=dt*(1+boost*4);viewScale+=(zoom*(1+boost*.2)-viewScale)*dt*1.8;for(const s of stars){const speed=dt*(.006+boost*.55)*s.z;s.x+=(s.x-cx)*speed;s.y+=(s.y-cy)*speed;if(s.x<-30||s.x>w+30||s.y<-30||s.y>h+30){s.x=cx+(Math.random()-.5)*w*.55;s.y=cy+(Math.random()-.5)*h*.55}}ripples.forEach(r=>{r.radius+=dt*95;r.life-=dt*.55});ripples=ripples.filter(r=>r.life>0);px+=(mx-px)*dt*3;py+=(my-py)*dt*3;if(trip>0){trip-=dt;if(trip<=0){targetBoost=0;document.body.classList.remove('traveling');document.querySelector('#travel').setAttribute('aria-busy','false');document.querySelector('#travel-label').textContent='Viajar por la galaxia'}}if(time>nextComet){comets.push({x:Math.random()*w*.6,y:Math.random()*h*.35,life:1});nextComet=time+6+Math.random()*8}comets.forEach(c=>{c.x+=dt*370;c.y+=dt*150;c.life-=dt*.6});comets=comets.filter(c=>c.life>0);sparks.forEach(s=>{s.x+=s.vx*dt*60;s.y+=s.vy*dt*60;s.life-=dt*.65});sparks=sparks.filter(s=>s.life>0);petals.forEach(p=>{p.y-=dt*12*p.s;p.x+=Math.sin(time*.3+p.a)*dt*5;if(p.y<-25){p.y=h+25;p.x=Math.random()*w}});render()}requestAnimationFrame(frame)}
function sync(){document.body.classList.toggle('paused',paused);motion.textContent=paused?'▷':'Ⅱ';motion.setAttribute('aria-pressed',String(paused));motion.setAttribute('aria-label',paused?'Reanudar animaciones':'Pausar animaciones');motion.title=motion.getAttribute('aria-label')}
motion.addEventListener('click',()=>{paused=!paused;sync()});media.addEventListener('change',e=>{paused=e.matches;sync();render()});document.querySelector('#travel').addEventListener('click',()=>{if(paused){paused=false;sync()}targetBoost=1;trip=7;document.querySelector('#travel').setAttribute('aria-busy','true');document.body.classList.add('traveling');document.querySelector('#travel-label').textContent='Viajando entre flores…';burst(cx,cy)});canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();cursorX=e.clientX-r.left;cursorY=e.clientY-r.top;mx=cursorX/w*2-1;my=cursorY/h*2-1});canvas.addEventListener('pointerleave',()=>{mx=0;my=0;cursorX=-1000;cursorY=-1000});canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect();burst(e.clientX-r.left,e.clientY-r.top)});const message=document.querySelector('#message');document.querySelector('#letter').addEventListener('click',()=>message.showModal());document.querySelector('#close').addEventListener('click',()=>message.close());message.addEventListener('click',e=>{if(e.target===message){const r=message.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)message.close()}});flower.onload=()=>{ready=true;render()};flower.src='flower.png';sun.onload=()=>{sunReady=true;render()};sun.src='sun.png';atlas.onload=()=>{atlasReady=true;render()};atlas.src='flowers-atlas.png';addEventListener('resize',resize);resize();sync();requestAnimationFrame(frame);

const welcome=document.querySelector('#welcome'),main=document.querySelector('.universe'),audio=document.querySelector('#audio'),music=document.querySelector('#music');audio.volume=.35;
function musicState(){const playing=!audio.paused;music.setAttribute('aria-pressed',String(playing));music.setAttribute('aria-label',playing?'Silenciar música':'Activar música');music.title=music.getAttribute('aria-label');music.textContent=playing?'♫':'♪'}
async function playMusic(){try{await audio.play()}catch{musicState()}musicState()}
document.querySelector('#enter').addEventListener('click',()=>{entered=true;document.body.classList.remove('onboarding');welcome.hidden=true;main.inert=false;playMusic();motion.focus()});document.querySelector('#home').addEventListener('click',()=>{entered=false;audio.pause();welcome.hidden=false;main.inert=true;document.body.classList.add('onboarding');document.querySelector('#enter').focus()});music.addEventListener('click',()=>{if(audio.paused)playMusic();else audio.pause()});audio.addEventListener('pause',musicState);audio.addEventListener('play',musicState);
function setZoom(value){zoom=Math.max(.45,Math.min(2.5,value));document.querySelector('#zoom-label').textContent=Math.round(zoom*100)+'%';if(paused){viewScale=zoom;render()}}
document.querySelector('#zoom-in').addEventListener('click',()=>setZoom(zoom*1.2));document.querySelector('#zoom-out').addEventListener('click',()=>setZoom(zoom/1.2));document.querySelector('#zoom-reset').addEventListener('click',()=>setZoom(1));canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom*Math.exp(-e.deltaY*.001))},{passive:false});const pointers=new Map();let pinch=0,pinchZoom=1;canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch')return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);if(pointers.size===2){const [a,b]=[...pointers.values()];pinch=Math.hypot(a.x-b.x,a.y-b.y);pinchZoom=zoom}});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&pinch>0){const [a,b]=[...pointers.values()];setZoom(pinchZoom*Math.hypot(a.x-b.x,a.y-b.y)/pinch)}});function release(e){pointers.delete(e.pointerId);pinch=0}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);musicState();
